apiVersion: apps/v1
kind: Deployment
metadata:
  name: AA ambitions
  labels:
    app: my-local-app
spec:
  selector:
    matchLabels:
      app: my-local-app
  template:
    metadata:
      labels:
        app: my-local-app
    spec:
      containers:
      - name: my-local-app-container
        image: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: my-local-app-service
  labels:
    app: my-local-app
spec:
  selector:
    app: my-local-app
  ports:
  - port: 5000
    targetPort: 5000
